# Generated by Django 5.2 on 2025-04-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
    ]
